on:
  release:
    types: [published]

name: Release

jobs:
  run_prerelease_tests:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - uses: actions/checkout@v2
      - name: Prepare environment
        uses: newrelic/puppet-install/.github/actions/installation@master
      - name: Run tests
        uses: newrelic/puppet-install/.github/actions/tests@master
  release_puppet:
    runs-on: ubuntu-latest
    name: Release puppet
    needs: run_prerelease_tests
    steps:
      - name: Release puppet
        uses: newrelic/puppet-install/.github/actions/release@master
        env:
          FORGE_API_KEY: ${{ secrets.FORGE_API_KEY }}

